openapi: 3.0.0
info:
  version: 0.0.1
  title: BCNNow Dashboard API
  contact:
    email: contact@example.com
    url: 'https://github.com/DECODEproject/bcnnow'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://decodeproject.eu/sites/default/files/favicon_13.png'
  description: >
    Documentation for the BCNNow dashboard API developed as part of the
    [DECODE](https://decodeproject.eu/) project

    # Introduction

    This API specification is to handle two scenarios:

    1. To create a new private community in the dashboard (either with encrypted
    data source or non-encrypted data source)

    2. To allow login using QR code and Mobile app.


    # Authentication


    The API currently does not require any authentication in order to submit
    requests.
tags:
  - name: Create Encrypted
    description: >-
      Endpoints that allow for the creation of new dashboards community with
      encrypted data sources
  - name: Create
    description: >-
      Endpoints that allow for the creation of new dashboards community with non
      encrypted data sources
  - name: IoT Login
    description: Endpoints that allow for login to dashbaord.
servers:
  - url: 'http://84.88.76.45:887'
  - url: 'http://93ff8837.ngrok.io'
